// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlexRequestsHosted.Infrastructure.Data;

#nullable disable

namespace PlexRequestsHosted.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260713051939_AddEpisodeAndMonitorFields")]
    partial class AddEpisodeAndMonitorFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.BridgeOutboxEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequesterUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("MediaRequestId");

                    b.ToTable("BridgeOutbox");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FulfillmentJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedEpisodesCsv")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSeasonsCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaRequestId");

                    b.HasIndex("Status");

                    b.ToTable("FulfillmentJobs");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AvailableAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequestAllSeasons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedEpisodesCsv")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSeasonsCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("MediaId", "MediaType");

                    b.ToTable("MediaRequests");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RelatedRequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.PlexMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.HasIndex("RatingKey");

                    b.ToTable("PlexMappings");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.PlexSeasonAvailabilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableEpisodesCsv")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShowRatingKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowRatingKey");

                    b.HasIndex("ShowRatingKey", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("PlexSeasonAvailability");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoplayTrailers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultQualityMovie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultQualityTV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultSort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DiscordDmOptIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MusicRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlexId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlexUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredProvider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredServerMachineId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredServerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAdultContent")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ThemeDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WatchedBadges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WhitelistStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PlexUsername");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.WatchlistItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("Username");

                    b.HasIndex("UserId", "MediaId", "MediaType");

                    b.ToTable("Watchlist");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.BridgeOutboxEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", "MediaRequest")
                        .WithMany()
                        .HasForeignKey("MediaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaRequest");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FulfillmentJobEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", "MediaRequest")
                        .WithMany()
                        .HasForeignKey("MediaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaRequest");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.NotificationEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", "RelatedRequest")
                        .WithMany()
                        .HasForeignKey("RelatedRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserProfileEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("PlexRequestsHosted.Infrastructure.Entities.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.WatchlistItemEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
