// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlexRequestsHosted.Infrastructure.Data;

#nullable disable

namespace PlexRequestsHosted.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260822083633_AddUserAccountLifecycle")]
    partial class AddUserAccountLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.AirScheduleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AirDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AirsAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeTitle")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasFile")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSearchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextSearchAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SearchAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SearchState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShowTmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceProvider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaRequestId");

                    b.HasIndex("NextSearchAt");

                    b.HasIndex("Monitored", "SearchState");

                    b.HasIndex("ShowTmdbId", "SeasonNumber", "EpisodeNumber")
                        .IsUnique();

                    b.ToTable("AirSchedule");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.BridgeOutboxEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestScopeKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequesterName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequesterUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("MediaRequestId");

                    b.HasIndex("AcknowledgedAt", "Id");

                    b.ToTable("BridgeOutbox");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.CustomFormatEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeWhenRenaming")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecificationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CustomFormats");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.CustomFormatScoreEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomFormatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomFormatId");

                    b.HasIndex("QualityProfileId", "CustomFormatId")
                        .IsUnique();

                    b.ToTable("CustomFormatScores");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.DownloadPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowEpisodeFallback")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoMonitorEntireSeriesRequests")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnforceQualityFloor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxEpisodesForFanout")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxSeasonPackSizeGb")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxSizeGb")
                        .HasColumnType("REAL");

                    b.Property<int>("MinSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MinTitleSimilarity")
                        .HasColumnType("REAL");

                    b.Property<bool>("PreferHdr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferHigherQualitySource")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreferX265")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreferredGroupsCsv")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("RelaxFloorAfterEmptySearches")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonPackStrategy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsSingleton")
                        .IsUnique();

                    b.ToTable("DownloadPreferences");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FirefoxCaptureDeviceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("BatchesReceived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtensionVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ItemsReceived")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCaptureAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastPageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastParserVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PairingId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PairingId")
                        .IsUnique();

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("IndexerId", "RevokedAt", "ExpiresAt");

                    b.ToTable("FirefoxCaptureDevices");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FirefoxCapturePairingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IndexerId");

                    b.ToTable("FirefoxCapturePairings");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FulfillmentJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionContextJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeferCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmptySearchCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Escalated")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ForcedIndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ForcedMagnet")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ForcedReleaseName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresCsv")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAnime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsManualGrab")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUpgrade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaIssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaKind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacePathsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestScopeKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedEpisodesCsv")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSeasonsCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonTargetsJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaIdentityId");

                    b.HasIndex("MediaRequestId")
                        .IsUnique()
                        .HasFilter("\"Status\" IN (0, 1, 2, 7)");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("Status");

                    b.HasIndex("MediaId", "MediaType");

                    b.ToTable("FulfillmentJobs");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FulfillmentTransferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("DownloadRateBytesPerSec")
                        .HasColumnType("REAL");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FailReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("FulfillmentJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NeededEpisodesCsv")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Peers")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Progress")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("ProgressChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seeds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("InfoHash");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackerStatus")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("TorrentId");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("State");

                    b.HasIndex("TransferId");

                    b.HasIndex("FulfillmentJobId", "Protocol", "TransferId")
                        .IsUnique();

                    b.ToTable("FulfillmentTorrents", (string)null);
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.ImportedFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomFormatScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestinationPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("FulfillmentJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualityDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResolutionHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransferId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("TorrentId");

                    b.HasKey("Id");

                    b.HasIndex("FulfillmentJobId");

                    b.ToTable("ImportedFiles");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.IndexerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnimeCategoriesCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AnimeOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrlOverride")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("CacheSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClearanceCookieEncrypted")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClearanceObtainedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAutomaticSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableIngestion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableInteractiveSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableRecommendedFeed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Implementation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastBlockReason")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastBlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("LastLatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastResultCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSearchAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaxAgeDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDetailFetches")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieCategoriesCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RateLimitPerMinute")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SearchCircuitOpenUntil")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonPackSeedTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("SeedRatio")
                        .HasColumnType("REAL");

                    b.Property<int?>("SeedTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsAnime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsMovie")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SupportsTv")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalResults")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSearches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TvCategoriesCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Implementation");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Enabled", "Priority");

                    b.ToTable("Indexers");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.IndexerMediaCapabilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoriesCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IndexerId", "MediaType")
                        .IsUnique();

                    b.ToTable("IndexerMediaCapabilities");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.JobRunEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduledJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TriggeredManually")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobType");

                    b.HasIndex("StartedAt");

                    b.ToTable("JobRuns");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.LibraryOrganizationPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioExtensionsCsv")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DeleteSourceAfterImport")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExtractArchives")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KeepSubtitles")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LibraryRootRulesJson")
                        .HasColumnType("TEXT");

                    b.Property<double>("MinAudioFileSizeMb")
                        .HasColumnType("REAL");

                    b.Property<double>("MinVideoFileSizeMb")
                        .HasColumnType("REAL");

                    b.Property<string>("MoviePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("MusicTrackTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("SeasonPackFolderTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SplitSeasonPacks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubtitleExtensionsCsv")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TransferMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TvEpisodeTemplate")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("TvPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoExtensionsCsv")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsSingleton")
                        .IsUnique();

                    b.ToTable("LibraryOrganizationPreferences");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaExternalIdentifierEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaIdentityId");

                    b.HasIndex("MediaType", "Kind", "Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("MediaExternalIdentifiers");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaIdentityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StableKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StableKey")
                        .IsUnique();

                    b.HasIndex("MediaType", "Kind");

                    b.ToTable("MediaIdentities");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaIssueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReplacementApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacementApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReplacementJobId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReplacementRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.ToTable("MediaIssues");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaMetadataCacheEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BackdropUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CardFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenresCsv")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Overview")
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalSeasons")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaIdentityId")
                        .IsUnique();

                    b.HasIndex("MediaType", "TmdbId")
                        .IsUnique()
                        .HasFilter("\"TmdbId\" > 0");

                    b.ToTable("MediaMetadataCache");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievedFormatScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AchievedQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AchievedQualityDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AirTimeOverrideMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoMonitorNewSeasons")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AvailableAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CutoffMet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DenialReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastMonitorCheckAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastUpgradeSearchAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonitorMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Monitored")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MonitoredSince")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MonitoringAnchorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MonitoringSeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RequestAllSeasons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestNote")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestScopeKind")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestedEpisodesCsv")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestedSeasonsCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("SearchForCutoffUpgrades")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("UpgradeAttempts")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaIdentityId");

                    b.HasIndex("RequestedAt");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("Status");

                    b.HasIndex("MediaId", "MediaType");

                    b.HasIndex("MonitoringAnchorId", "MonitoringSeasonNumber")
                        .IsUnique();

                    b.HasIndex("Status", "MediaType");

                    b.HasIndex("Monitored", "MediaType", "Status");

                    b.ToTable("MediaRequests");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MonitoringPreferencesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AirTimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssumedAirTimeLocal")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int>("CalendarBackfillDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalendarHorizonDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxSearchAttemptsPerEpisode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PostAirDelayMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsSingleton")
                        .IsUnique();

                    b.ToTable("MonitoringPreferences");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MusicSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CatalogEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DirectDownloadsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSingleton")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequestsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsSingleton")
                        .IsUnique();

                    b.ToTable("MusicSettings");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.NetworkShareEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domain")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MountSlug")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordProtected")
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShareName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MountSlug")
                        .IsUnique();

                    b.ToTable("NetworkShares");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RelatedRequestId");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.PlexMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioCodec")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MissedScans")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RatingKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VideoCodec")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoResolution")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExternalKey")
                        .IsUnique();

                    b.HasIndex("RatingKey");

                    b.ToTable("PlexMappings");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.PlexSeasonAvailabilityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvailableEpisodesCsv")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("EpisodeCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodeQualityJson")
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissedScans")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShowRatingKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowRatingKey");

                    b.HasIndex("ShowRatingKey", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("PlexSeasonAvailability");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.ProfileAssignmentRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchGenre")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchLibrary")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchMediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchTmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.HasIndex("QualityProfileId");

                    b.ToTable("ProfileAssignmentRules");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.QualityDefinitionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MaxSizeGb")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinSizeGb")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortWeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortWeight");

                    b.HasIndex("Resolution", "Source")
                        .IsUnique();

                    b.ToTable("QualityDefinitions");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.QualityProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedLanguagesCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("AppliesToMediaTypes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CutoffFormatScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CutoffQualityDefinitionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUserSelectable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxSeasonPackSizeGb")
                        .HasColumnType("REAL");

                    b.Property<double?>("MaxSizeGb")
                        .HasColumnType("REAL");

                    b.Property<int>("MinCustomFormatScore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinSeeders")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("MinSizeGb")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UpgradeAllowed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDefault");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("QualityProfiles");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.QualityRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MatchGenre")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchLibrary")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MatchMediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MatchTmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetQuality")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Order");

                    b.ToTable("QualityRules");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.RecommendedItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PosterUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceIndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SourceYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("TmdbId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Rank");

                    b.HasIndex("SeenAt");

                    b.HasIndex("TmdbId", "MediaType")
                        .IsUnique();

                    b.ToTable("RecommendedItems");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.ReleaseBlocklistEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BlockedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detail")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InfoHash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedReleaseName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Protocol")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Reason")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseName")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("Scope")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash");

                    b.HasIndex("NormalizedReleaseName");

                    b.HasIndex("InfoHash", "MediaRequestId")
                        .IsUnique();

                    b.HasIndex("MediaId", "MediaType");

                    b.HasIndex("Protocol", "SourceId");

                    b.HasIndex("Protocol", "SourceId", "MediaRequestId")
                        .IsUnique();

                    b.ToTable("ReleaseBlocklist");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.ScheduledJobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastRunDurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ManualRunRequested")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRunAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RunningSince")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JobType")
                        .IsUnique();

                    b.HasIndex("NextRunAt");

                    b.ToTable("ScheduledJobs");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.SearchTaskEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcquisitionContextJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapabilitiesJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClaimedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSource")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeRejected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IndexerOutcomesJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaRequestId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QualityProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestScopeKind")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RequestedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResultsJson")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("MediaRequestId");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("SearchTasks");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.SeasonEpisodesCacheEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EpisodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeasonNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShowTmdbId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ShowTmdbId", "SeasonNumber")
                        .IsUnique();

                    b.ToTable("SeasonEpisodesCache");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllowedQualityProfileIdsCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MovieRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieRequestLimitDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MusicRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicRequestLimitDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvRequestLimitDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AccountStatusChangedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountStatusChangedBy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountStatusReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedQualityProfileIdsCsv")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoApprove")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoplayTrailers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultQualityMovie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultQualityProfileIdMovie")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultQualityProfileIdTv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultQualityTV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefaultSort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DiscordDmOptIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MovieRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieRequestLimitDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MusicRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MusicRequestLimitDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Permissions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlexId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PlexUsername")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredProvider")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredServerMachineId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredServerName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("Roles")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowAdultContent")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SuspendedUntil")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ThemeDarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TvRequestLimit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TvRequestLimitDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WatchedBadges")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasFilter("\"DiscordUserId\" IS NOT NULL");

                    b.HasIndex("PlexUsername");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.WatchlistItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MediaIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("MediaIdentityId");

                    b.HasIndex("Username");

                    b.HasIndex("UserId", "MediaId", "MediaType");

                    b.ToTable("Watchlist");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.BridgeOutboxEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", "MediaRequest")
                        .WithMany()
                        .HasForeignKey("MediaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaRequest");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.CustomFormatScoreEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.CustomFormatEntity", null)
                        .WithMany()
                        .HasForeignKey("CustomFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.QualityProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("QualityProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FirefoxCaptureDeviceEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.IndexerEntity", "Indexer")
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.FirefoxCapturePairingEntity", "Pairing")
                        .WithMany()
                        .HasForeignKey("PairingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexer");

                    b.Navigation("Pairing");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FirefoxCapturePairingEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.IndexerEntity", "Indexer")
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexer");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FulfillmentJobEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaIdentityEntity", "MediaIdentity")
                        .WithMany()
                        .HasForeignKey("MediaIdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", "MediaRequest")
                        .WithMany()
                        .HasForeignKey("MediaRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaIdentity");

                    b.Navigation("MediaRequest");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.FulfillmentTransferEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.FulfillmentJobEntity", "Job")
                        .WithMany()
                        .HasForeignKey("FulfillmentJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.ImportedFileEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.FulfillmentJobEntity", "FulfillmentJob")
                        .WithMany()
                        .HasForeignKey("FulfillmentJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FulfillmentJob");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.IndexerMediaCapabilityEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.IndexerEntity", "Indexer")
                        .WithMany("MediaCapabilities")
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexer");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaExternalIdentifierEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaIdentityEntity", "MediaIdentity")
                        .WithMany("ExternalIdentifiers")
                        .HasForeignKey("MediaIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaIdentity");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaMetadataCacheEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaIdentityEntity", "MediaIdentity")
                        .WithMany()
                        .HasForeignKey("MediaIdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MediaIdentity");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaIdentityEntity", "MediaIdentity")
                        .WithMany()
                        .HasForeignKey("MediaIdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MediaIdentity");

                    b.Navigation("RequestedByUser");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.NotificationEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaRequestEntity", "RelatedRequest")
                        .WithMany()
                        .HasForeignKey("RelatedRequestId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RelatedRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.ProfileAssignmentRuleEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.QualityProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("QualityProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserProfileEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserGroupEntity", "UserGroup")
                        .WithMany("Members")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("PlexRequestsHosted.Infrastructure.Entities.UserProfileEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.WatchlistItemEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.MediaIdentityEntity", "MediaIdentity")
                        .WithMany()
                        .HasForeignKey("MediaIdentityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PlexRequestsHosted.Infrastructure.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MediaIdentity");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.IndexerEntity", b =>
                {
                    b.Navigation("MediaCapabilities");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.MediaIdentityEntity", b =>
                {
                    b.Navigation("ExternalIdentifiers");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Entities.UserGroupEntity", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
