// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlexRequestsHosted.Infrastructure.Catalog;

#nullable disable

namespace PlexRequestsHosted.Infrastructure.Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260816014819_InitialCatalog")]
    partial class InitialCatalog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Catalog.CatalogBatchReceiptEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BatchId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CommittedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommittedAt");

                    b.HasIndex("IndexerId", "BatchId")
                        .IsUnique();

                    b.ToTable("BatchReceipts");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Catalog.CatalogCheckpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CircuitState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cursor")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastBatchId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalItemsResolved")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalItemsSeen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IndexerId")
                        .IsUnique();

                    b.HasIndex("NextAttemptAt");

                    b.ToTable("Checkpoints");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Catalog.CatalogReleaseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Episode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EpisodeStart")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImdbId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleteSeries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeasonPack")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MagnetUri")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MediaType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ParserVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseSource")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Season")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SeasonEnd")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InfoHash")
                        .IsUnique();

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("NormalizedTitle");

                    b.HasIndex("Season", "Episode");

                    b.ToTable("Releases");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Catalog.CatalogSightingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HydrationError")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("HydrationState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndexerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastHydratedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Leechers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ReleaseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReleaseName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Seeders")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uploader")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HydrationState");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("ReleaseId");

                    b.HasIndex("IndexerId", "ExternalId")
                        .IsUnique();

                    b.ToTable("Sightings");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Catalog.CatalogSightingEntity", b =>
                {
                    b.HasOne("PlexRequestsHosted.Infrastructure.Catalog.CatalogReleaseEntity", "Release")
                        .WithMany("Sightings")
                        .HasForeignKey("ReleaseId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Release");
                });

            modelBuilder.Entity("PlexRequestsHosted.Infrastructure.Catalog.CatalogReleaseEntity", b =>
                {
                    b.Navigation("Sightings");
                });
#pragma warning restore 612, 618
        }
    }
}
